# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swedish Embedded Group
email: info@swedishembedded.com
description: "Superpowers For Embedded Engineers"
subtitle: "Swedish Embedded Ninja Podcast"
lang: en-us
author: Martin K. Schröder
copyright: "&#xA9; 2015"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swedishembedded.com" # the base hostname & protocol for your site
twitter_username: martin.k.schroder
github_username:  mkschreder

permalink: /:year/:title.html

#Timezone
timezone: Sweden/Stockholm

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']
